language: ruby
cache: bundler
rvm:
- 2.2.0
sudo: false
script: bundle exec rake deploy
env:
  global:
    secure: pwoWb/17pFr/kpZkaylnX7fZBKhL/tVKMHRTd5/fZJ3cS1yb13uKG8Fia9/8I1CsNARlUbYZ7m+vDHQpHzfX/0u8mYdncXg7Lc1rA5eZdnYwlIFwB5Jvl6uzRXuRx4Q0FftnOOrjrMC0P/6Sx3qacvjw70jkOQ/nLVB+AJTIBRArN/Bo8gnc2oQkcYZOvW1BHq37vU7nkCFYGRW2YbxZftiTqO8YfHrJh/7hHOMXTQFOi+HDCuDpsQycffkaGxSg2JxHKBj8SurgIrtNLN/JjAkA+IaTvNz3047PEn7CTyUKJRodS7hns25wLnFym4xNkI45s+R7xaIasCqSpjP1Um6fBW0CTQzoGWt/FJ26wZcBevGtYaB6WW6biWaDjIqou6j8vWmEOVSFAusCIypJNrIz47gZs/8M1KVcAdTEbNI0eGVn8A5VcqxJ2AUROtmsYjLUYw2F0WKAE1b5qHE0zL9nX6hFSsRZMBhc5B7B8cw2fEHGjd1m5uzo1SM9+VqqsJw74E9lgLoC76hBeLEF8XjksEifLV3SJewvOqgEN9TqhAbDyxWV7OzF2l2HH3RFyG9h1D+quuIEoiclbnqSQ6IOlGNlubMeopoWmzb0/ujcLHLNuMKTRbO8GXb+5QytbWcYzHDAYJL/0OpjI0hlvZ9YTGqdx7D6w/sPgJes+yk=
