= https://rmpestano.github.io/site/[RSJUG Site^]
:page-layout: base
:source-language: java
:icons: font
:linkattrs:
:sectanchors:
:sectlink:
:!numbered:
:doctype: book
:toc: preamble
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:

== What's it?

A try to migrate http://www.rsjug.org/[RSJUG site^] to  https://jekyllrb.com/[Jekyll] and github pages.

==  Features

* Responsive layout
* Mobile 'friendly'
* https://disqus.com/[Disqus] integration
* Based on github pages 
* Promotes contribution (as it is hosted in github)
* Automatically build on git push
* Posts based on Asciidoc (via asciidoctor.org/[Asciidoctor] and https://guides.github.com/features/mastering-markdown/[Markdown] (focus on content instead of markup)


== Running it locally

. Fist you will need to https://www.ruby-lang.org/en/documentation/installation/[install Ruby^]
+
NOTE: Use `Ruby 2.1` or superior
. Install `Bundler` gem:
+ 
----
gem install bundler
----
+
TIP: You can skip this step if you want to install gems individually, see https://github.com/rmpestano/site/blob/master/Gemfile.xml[requied gems here]
. Clone the project:
+
----
git clone https://github.com/rmpestano/site rsjug-site
cd rsjug-site
----
. Run 
+
----
bundle install
----
+
NOTE: It will install gems declared in `Gemfile`. You can skip this step if gems are already installed
+
IMPORTANT: If you receive the error `can't find header files for ruby at /usr/share/include/ruby.h` you need to install ruby development kit in your operating system:
+
----
//fedora
sudo dnf install -y gcc ruby-devel rubygems libxml2 libxml2-devel libxslt libxslt-devel
//ubuntu
sudo apt-get install ruby-dev 
//or
sudo apt-get install ruby2.0-dev
//or
sudo apt-get install ruby2.2-dev
----
+
IMPORTANT: if you get `ERROR: Failed to build gem native extension.`, you need to install native extensions:
+
----
//ubuntu
sudo apt-get install libgmp-dev
//or
sudo apt-get install libgmp3-dev
//fedora
sudo dnf install rpm-build
----
+
NOTE: output should be:
+
----
Bundle complete! 7 Gemfile dependencies, 27 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
----
. Then run Jekyll 
+
----
jekyll serve
----
. And finally access http://localhost:4000/site/


TIP: Every file change is automatically published locally by Jekyll.


== TODO

* Search mechanism to find posts
* Customize layout (preferably by a web designer)

